### ISSUE TITLE
crashes

### ISSUE THREAD

**Issue by nemoo88** [jaxcksn/nanoleafMusic#16]
program crash when trying to make it work with spotify. nanoleaf hexagon

**Comment by jaxcksn** [comment]
Hi, at this time Hexagons are not supported. The only supported products are the Canvas and Light Panels (aka Aurora).

**Comment by nemoo88** [comment]
when will hexagons be added?

**Comment by jaxcksn** [comment]
Unlikely to be anytime soon as I don't own the hexagons, and the API isn't documented by Nanoleaf yet.

**Comment by nemoo88** [comment]
https://github.com/MylesMor/nanoleafapi

**Comment by nemoo88** [comment]
https://forum.nanoleaf.me/forum/community-support/hexagon-shapes-and-open-api

**Comment by jaxcksn** [comment]
That's a wrapper for existing endpoints, I need documentation on layout data and there's still the issue of testing.

It's possible and planned for a future release, just not anytime soon.
