### ISSUE TITLE
[REQUEST] Manual IP Configuration

### ISSUE THREAD

**Issue by jbechtel1089** [jaxcksn/nanoleafMusic#19]
Could not properly get my Nanoleaf Shapes to connect to the application. Would appreciate a manual connection configuration option where I have the availability to enter the proper IP and port of my Shapes.

**Comment by jaxcksn** [comment]
I have this planned out as a feature for the new version of this program, however, this version program isn't compatible with Shapes anyway so typing in the IP and port manually wouldn't do much good.
