### ISSUE TITLE
[REQUEST] add a linux installer

### ISSUE THREAD

**Issue by bryceorchard** [jaxcksn/nanoleafMusic#22]
**Is your feature request related to a problem? Please describe.**
It's a pain in the ass to install it through wine and mess with configs

**Describe the solution you'd like**
Adding a linux installer would be great

**Comment by Ry-DS** [comment]
This is a Java application. Can't you just run the JAR?

Edit: Sorry, didn't notice that a JAR isn't given in the install options. Might be a good idea for the maintainer to provide a JAR since it's quite easy to produce with JavaFX.

**Comment by jaxcksn** [comment]
Planned for #23
