### ISSUE TITLE
Effect randomly stops until it is reloaded

### ISSUE THREAD

**Issue by jaxcksn** [jaxcksn/nanoleafMusic#9]
**Describe the bug**
The playing effect will randomly stop displaying itself on the connected device. The UI will still update, and no exceptions are thrown.

**To Reproduce**
This bug is particularly problematic because it is very difficult to reproduce. It seems to be almost random.

**Desktop (please complete the following information):**
 - OS: macOS and Windows
 - Version: v1.0 and v1.1-b

**Nanoleaf Device (please complete the following information):**
- Type of Device: Light Panels

**Additional context**
I'm working on more verbose logging in #8 and when I start testing I will include a method to dump a bunch of data on an effect reload so that the next time I encounter it I can get some insight into what is happening.

**Comment by ProfessoRJ13** [comment]
Also happens to canvas panels!

**Comment by jaxcksn** [comment]
Windows seems to be effected more by this bug than MacOS as noted in https://github.com/jaxcksn/nanoleafMusic/issues/12#issuecomment-766537585

My goal is to hopefully have this fixed by v1.5, its still proving difficult to reproduce, and the logging data I've been collecting isn't showing any issues with the logic causing this issue. I'm going to spend some time profiling and doing some advanced debugging to get to the bottom of this issue. I'm thinking it might be cause by some sort of issue with the scheduled executor service.

**Comment by jaxcksn** [comment]
So I think I've found one cause of the issue. The scheduled thread pool executor was failing silently, because another silent exception caused by RGB values being higher than 255 when initialized was blocking some of the threads and causing the thread pool to run out of threads.

It explains some of the weirdness:
- Windows being effected more because of differences in Thread Pool sizes.
- Reloading fixed the problem because the executor is restarted in the reload process.
- No exceptions were thrown because the exception that was blocking the process was silent.
- It seemed random because the exceptions would only be thrown on album art with bright colors, and would need to happen several times.

I'm gonna patch this, and test to see if the bug persists.
